version: '3'
services:
  my-go-service:
    build: .
    ports:
      - "80:80"
    networks:
      - botmailnet
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bot_data
      MYSQL_USER: bot
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
networks:
  botmailnet:
    driver: bridge
